### ISSUE TITLE
Component 'BambuserBroadcasterView' re-reregistered direct event 'topPictureSaved' as a bubbling event

### ISSUE THREAD

**Issue by snobear** [bambuser/react-native-bambuser-broadcaster#20] opened 2020-01-19 15:36 UTC
Hi, I'm getting the following error when trying out `react-native-bambuser-broadcaster` on iOS:

```
Component 'BambuserBroadcasterView' re-reregistered direct event 'topPictureSaved' as a bubbling event
```

![Screenshot 2020-01-19 at 10 28 13 AM](https://user-images.githubusercontent.com/696230/72683572-847d2e80-3aa6-11ea-94bf-4fe0ff59427c.png)

This happens as soon as I build and run the app from Xcode on my device (iPhone 7+, iOS 13.3).

Here is my screen component:

```javascript
import { Button } from 'react-native';
import React from 'react';
import { ContentArea } from '../../../Common/components/Boxes';
import RNBambuserBroadcaster from 'react-native-bambuser-broadcaster';

const StreamTest = (props) => {
  return (
    <ContentArea>
      <RNBambuserBroadcaster
        ref={ref => {this.myBroadcasterRef = ref; }}
        applicationId='secret' />
      <Button
        title='Start broadcast'
        onPress={() => this.myBroadcasterRef.startBroadcast()} />
    </ContentArea>
  )
}

export default StreamTest;
```

Here are the pod versions I have installed per `Podfile.lock`:

```
  - libbambuser-ios (0.9.24)
  - react-native-bambuser-broadcaster (0.0.11):
```

*React Native info*

```
$ react-native info
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz
    Memory: 16.14 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.1 => 16.8.1 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

*Install Steps*

Update podspec per #19 then:

```
yarn add react-native-bambuser-broadcaster --save
cd ios && pod install && cd ..
```

Then in Xcode, build and run on device and you should get the error.

I'm unable to get a broadcast started at the present moment, so I'm wondering if its related to this error, as `libbambuser-ios` is likely the culprit and probably crashing.

**Comment by peterlofquist** [comment] 2020-01-20 09:51
I can't reproduce this issue with a clean install. From what I'm reading from other react-native components which had an similar issues is that some other component might also use the event name `PictureSaved` in the form of a `RCTBubblingEventBlock,` and therefor present this issue.

It would be very helpful if you could try out this branch with your current project and see if you still receives this error: https://github.com/bambuser/react-native-bambuser-broadcaster/tree/direct-event

**Comment by snobear** [comment] 2020-01-20 21:37
Hi @peterlofquist, thanks for the info. That makes sense. I'm confused on the name scheme though. I searched for `PictureSaved` and `topPictureSaved`, but not finding anything. Would the event be called `onPictureSaved`? If so, I think the conflict is in react-native-camera:

https://github.com/react-native-community/react-native-camera/blob/fe5d11d12fe2a7eb7d0582776f260415f1b2865b/ios/RN/RNCameraManager.m#L23

**Comment by snobear** [comment] 2020-01-20 22:05
I commented that line out in `node_modules/react-native-camera/ios/RN/RNCameraManager.m` but now getting a new conflict:

![image](https://user-images.githubusercontent.com/696230/72760368-83332b00-3ba6-11ea-8142-2e2f1f49f488.png)

I assume there is no way to get around the conflicts, other than for me to maintain a fork of either this lib or react-native-camera :(. Shame that React Native doesn't have a better system for avoiding conflicts, then again I'm not familiar enough with it to comment probably :D. Let me know if you have any thoughts on workarounds.

**Comment by peterlofquist** [comment] 2020-01-21 08:25
Maybe React-Native do some magic with event names to match some kind of internal protocol. I'll update https://github.com/bambuser/react-native-bambuser-broadcaster/tree/direct-event during the day to change more `RCTBubblingEventBlock` to `RCTDirectEventBlock` which might help to mitigate this issue.

If that doesn't help I guess we'll need to add an unique naming our event names anymore. 🙃

**Comment by snobear** [comment] 2020-01-21 15:11
OK sorry you have to rename things!  On another note, I tried with a fresh RN project per RN docs:

```
npx react-native init AwesomeProject
yarn add react-native-bambuser-broadcaster
cd ios && pod install && cd ..
```

Then added entries to `Info.plist` for:
- Privacy - Camera Usage Description
- Privacy - Microphone Usage Description

Then changed App.js to:

```
// App.js
import React from 'react';
import {
  SafeAreaView,
  StatusBar,
  Button
} from 'react-native';
import RNBambuserBroadcaster from 'react-native-bambuser-broadcaster';

const App: () => React$Node = () => {
  startBroadcast = () => {
    console.log('starting broadcast');
    console.log('this.myBroadcasterRef.startBroadcast',this.myBroadcasterRef.startBroadcast());
    this.myBroadcasterRef.startBroadcast();
  }

  return (
    <SafeAreaView>
      <Button
        title='Start broadcast'
        onPress={() => startBroadcast()} />
      <RNBambuserBroadcaster
        ref={ref => {this.myBroadcasterRef = ref }}
        onBroadcastStarted={() => console.log('onBroadcastStarted')}
        onBroadcastError={(e) => console.log('onBroadcastError',e)}
        applicationId='ccmYPeLXIxs5J3dMgZj7Tw' />
    </SafeAreaView>
  );
};

export default App;
```

However when I tap the button, nothing is happening and logs indicated `this.myBroadcasterRef.startBroadcast()` is undefined. Did I miss a step for iOS, perhaps something needs to be added to the AppDelegate?

I'll open up a separate issue if preferred.

**Comment by peterlofquist** [comment] 2020-01-22 05:40
I've updated the branch above(https://github.com/bambuser/react-native-bambuser-broadcaster/tree/direct-event) to also change the `onCameraReady` to a `RCTDirectEventBlock` property to see if that solves the `topCameraReady` issue. I'll try to reproduce this issue shortly.

I tested the code above and it worked fine. `onBroadcastError` should be triggered if the broadcast couldn't invoke the `startBroadcast` function.

And to answer why `this.myBroadcasterRef.startBroadcast()` is undefined is because this function doesn't return any value, so when invoked the function is intended to not return anything. If you however remove the function call there and just log `this.myBroadcasterRef.startBroadcast` you should see a javascript function like this `[Function: startBroadcast]`.

I tested with the following setup:
```
$ react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 75.07 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.16.0 - /usr/local/opt/node@8/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by snobear** [comment] 2020-01-27 19:14
Thanks @peterlofquist . Just a heads up I'm tied up at the moment, but plan on revisiting this shortly to test.

**Comment by felippepuhle** [comment] 2020-02-11 17:31
We're using `react-native-camera` and after installing `react-native-bambuser-broadcaster` we got `Component 'RNCamera' re-registered bubbling event 'topPictureSaved' as a direct event`

I think there is some event name conflict, see https://github.com/react-native-community/react-native-camera/issues/2620

**Comment by peterlofquist** [comment] 2020-02-14 12:59
@felippepuhle there's a potential fix for this issue in this branch: https://github.com/bambuser/react-native-bambuser-broadcaster/tree/direct-event

If you can please test that out and verify that this solves the naming conflict issue with react-native-camera I'll make sure to update our component with the branch mentioned above.

**Comment by felippepuhle** [comment] 2020-02-14 15:35
@peterlofquist I'll take a look later on, thanks!

**Comment by jrfurini** [comment] 2020-02-18 12:11
Hi @peterlofquist , I am using Bambuser as a producer and inclued RNCamera in other screen and got this error explained at first message.

I followed your commit "1c607d62f2e9073f45a2dec9f7697b6805c95aef", changing files "BambuserBroadcasterViewManager.m" and "BambuserBroadcasterView.h" and everything worked fine.

Thanks.

Please let me know when it is a final version

**Comment by felippepuhle** [comment] 2020-02-18 13:10
Yes! It seems to be working here too! Thanks guys!

**Comment by jrfurini** [comment] 2020-02-21 10:32
Hi @peterlofquist , I am using Bambuser with RNCamera and CameraRoll too. After these changes in my code, I couldn't save pictures at CameraRoll. Videos are ok, I can save videos after Live Stream right.

**Comment by peterlofquist** [comment] 2020-02-26 09:40
> Hi @peterlofquist , I am using Bambuser with RNCamera and CameraRoll too. After these changes in my code, I couldn't save pictures at CameraRoll.

I am not quite sure I follow what your issue is here.

I tried with `react-native-camera` & `CameraRoll` linked to the same project as `react-native-bambuser-broadcaster` and I could save pictures taken with `react-native-camera` with `CameraRoll` just fine.

> Videos are ok, I can save videos after Live Stream right.

Can you explain a bit further what you mean with 'save videos after live stream'?

**Comment by peterlofquist** [comment] 2020-02-26 12:33
@jrfurini I found that CameraRoll expected to get a file url instead of path in order to save images. I updated version 0.0.15 to instead give you a proper file URL, just like the onLocalCopySaved callback returns.

 0.0.15 also includes the switch from bubbling to direct events, and hence everyones issues in here should be solved. Closing issue and feel free to open if any errors still occur.

**Closed by peterlofquist** 2020-02-26 12:33 UTC
